CREATE TABLE IF NOT EXISTS scheduled_command (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    time TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS interval_command (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    interval INTERVAL NOT NULL
);
