// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go
//
// Generated by this command:
//
//	mockgen -source=contracts.go -destination=./mocks_usecase_test.go -package=usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	entity "github.com/dorozhkoanton/battletoads/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockTranslation is a mock of Translation interface.
type MockTranslation struct {
	ctrl     *gomock.Controller
	recorder *MockTranslationMockRecorder
	isgomock struct{}
}

// MockTranslationMockRecorder is the mock recorder for MockTranslation.
type MockTranslationMockRecorder struct {
	mock *MockTranslation
}

// NewMockTranslation creates a new mock instance.
func NewMockTranslation(ctrl *gomock.Controller) *MockTranslation {
	mock := &MockTranslation{ctrl: ctrl}
	mock.recorder = &MockTranslationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranslation) EXPECT() *MockTranslationMockRecorder {
	return m.recorder
}

// History mocks base method.
func (m *MockTranslation) History(arg0 context.Context) ([]entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "History", arg0)
	ret0, _ := ret[0].([]entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// History indicates an expected call of History.
func (mr *MockTranslationMockRecorder) History(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "History", reflect.TypeOf((*MockTranslation)(nil).History), arg0)
}

// Translate mocks base method.
func (m *MockTranslation) Translate(arg0 context.Context, arg1 entity.Translation) (entity.Translation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Translate", arg0, arg1)
	ret0, _ := ret[0].(entity.Translation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Translate indicates an expected call of Translate.
func (mr *MockTranslationMockRecorder) Translate(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockTranslation)(nil).Translate), arg0, arg1)
}

// MockIntervalCommand is a mock of IntervalCommand interface.
type MockIntervalCommand struct {
	ctrl     *gomock.Controller
	recorder *MockIntervalCommandMockRecorder
	isgomock struct{}
}

// MockIntervalCommandMockRecorder is the mock recorder for MockIntervalCommand.
type MockIntervalCommandMockRecorder struct {
	mock *MockIntervalCommand
}

// NewMockIntervalCommand creates a new mock instance.
func NewMockIntervalCommand(ctrl *gomock.Controller) *MockIntervalCommand {
	mock := &MockIntervalCommand{ctrl: ctrl}
	mock.recorder = &MockIntervalCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIntervalCommand) EXPECT() *MockIntervalCommandMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIntervalCommand) Create(arg0 context.Context, arg1 entity.IntervalCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIntervalCommandMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIntervalCommand)(nil).Create), arg0, arg1)
}

// MockScheduledCommand is a mock of ScheduledCommand interface.
type MockScheduledCommand struct {
	ctrl     *gomock.Controller
	recorder *MockScheduledCommandMockRecorder
	isgomock struct{}
}

// MockScheduledCommandMockRecorder is the mock recorder for MockScheduledCommand.
type MockScheduledCommandMockRecorder struct {
	mock *MockScheduledCommand
}

// NewMockScheduledCommand creates a new mock instance.
func NewMockScheduledCommand(ctrl *gomock.Controller) *MockScheduledCommand {
	mock := &MockScheduledCommand{ctrl: ctrl}
	mock.recorder = &MockScheduledCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduledCommand) EXPECT() *MockScheduledCommandMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockScheduledCommand) Create(arg0 context.Context, arg1 entity.ScheduledCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockScheduledCommandMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockScheduledCommand)(nil).Create), arg0, arg1)
}
